<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConfeitariasSeeder extends Seeder
{
    public function run()
    {
        // Criar 15 registros de confeitarias
        DB::table('confeitarias')->insert([
            [
                'nome' => 'Doce Magia',
                'telefone' => '11 99999-9999',
                'cep' => '12345-678',
                'rua' => 'Rua das Confeiteiras',
                'numero' => '123',
                'complemento' => 'Loja 2',
                'bairro' => 'Jardim das Flores',
                'cidade' => 'São Paulo',
                'estado' => 'SP',
                'latitude' => -23.5558,
                'longitude' => -46.6396,
            ],
            [
                'nome' => 'Doces & Cia',
                'telefone' => '11 98888-8888',
                'cep' => '23456-789',
                'rua' => 'Rua dos Doces',
                'numero' => '456',
                'complemento' => 'Loja 1',
                'bairro' => 'Centro',
                'cidade' => 'São Paulo',
                'estado' => 'SP',
                'latitude' => -23.5500,
                'longitude' => -46.6339,
            ],
            [
                'nome' => 'Delícias da Vovó',
                'telefone' => '21 97777-7777',
                'cep' => '34567-890',
                'rua' => 'Avenida das Rosas',
                'numero' => '789',
                'complemento' => 'Casa 5',
                'bairro' => 'Vila das Laranjeiras',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'latitude' => -22.9028,
                'longitude' => -43.2075,
            ],
            [
                'nome' => 'Café & Doces',
                'telefone' => '21 95555-5555',
                'cep' => '45678-901',
                'rua' => 'Rua das Belezas',
                'numero' => '321',
                'complemento' => '',
                'bairro' => 'Botafogo',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'latitude' => -22.9560,
                'longitude' => -43.1791,
            ],
            [
                'nome' => 'Sabor da Terra',
                'telefone' => '31 94444-4444',
                'cep' => '56789-012',
                'rua' => 'Rua das Margaridas',
                'numero' => '654',
                'complemento' => 'Loja 10',
                'bairro' => 'Savassi',
                'cidade' => 'Belo Horizonte',
                'estado' => 'MG',
                'latitude' => -19.9326,
                'longitude' => -43.9409,
            ],
            [
                'nome' => 'Doce Encanto',
                'telefone' => '11 92222-2222',
                'cep' => '67890-123',
                'rua' => 'Avenida das Laranjeiras',
                'numero' => '123',
                'complemento' => '',
                'bairro' => 'Vila Progresso',
                'cidade' => 'São Paulo',
                'estado' => 'SP',
                'latitude' => -23.5556,
                'longitude' => -46.6395,
            ],
            [
                'nome' => 'Açúcar & Canela',
                'telefone' => '41 93333-3333',
                'cep' => '78901-234',
                'rua' => 'Rua das Acácias',
                'numero' => '111',
                'complemento' => '',
                'bairro' => 'Centro',
                'cidade' => 'Curitiba',
                'estado' => 'PR',
                'latitude' => -25.4297,
                'longitude' => -49.2713,
            ],
            [
                'nome' => 'Cacau Delícias',
                'telefone' => '61 94444-4444',
                'cep' => '89012-345',
                'rua' => 'Rua do Chocolate',
                'numero' => '234',
                'complemento' => '',
                'bairro' => 'Águas Claras',
                'cidade' => 'Brasília',
                'estado' => 'DF',
                'latitude' => -15.7801,
                'longitude' => -47.9292,
            ],
            [
                'nome' => 'Guloseimas da Tia',
                'telefone' => '51 95555-5555',
                'cep' => '90123-456',
                'rua' => 'Rua dos Sabores',
                'numero' => '567',
                'complemento' => '',
                'bairro' => 'Moinhos de Vento',
                'cidade' => 'Porto Alegre',
                'estado' => 'RS',
                'latitude' => -30.0330,
                'longitude' => -51.2300,
            ],
            [
                'nome' => 'Bolos e Trufas',
                'telefone' => '71 96666-6666',
                'cep' => '01234-567',
                'rua' => 'Avenida das Trufas',
                'numero' => '890',
                'complemento' => 'Loja 2',
                'bairro' => 'Pituba',
                'cidade' => 'Salvador',
                'estado' => 'BA',
                'latitude' => -12.9730,
                'longitude' => -38.4983,
            ],
            [
                'nome' => 'Torta Mágica',
                'telefone' => '85 92222-2222',
                'cep' => '12345-678',
                'rua' => 'Rua das Noivas',
                'numero' => '234',
                'complemento' => '',
                'bairro' => 'Aldeota',
                'cidade' => 'Fortaleza',
                'estado' => 'CE',
                'latitude' => -3.7172,
                'longitude' => -38.5437,
            ],
            [
                'nome' => 'Confeitaria Doce Vida',
                'telefone' => '27 93333-3333',
                'cep' => '23456-789',
                'rua' => 'Rua das Pedras',
                'numero' => '345',
                'complemento' => '',
                'bairro' => 'Jardim da Penha',
                'cidade' => 'Vitória',
                'estado' => 'ES',
                'latitude' => -20.3155,
                'longitude' => -40.3128,
            ],
            [
                'nome' => 'Aromas & Sabores',
                'telefone' => '62 94444-4444',
                'cep' => '34567-890',
                'rua' => 'Avenida dos Aromas',
                'numero' => '456',
                'complemento' => '',
                'bairro' => 'Setor Bueno',
                'cidade' => 'Goiânia',
                'estado' => 'GO',
                'latitude' => -16.6789,
                'longitude' => -49.2644,
            ],
            [
                'nome' => 'Doces da Terra',
                'telefone' => '31 95555-5555',
                'cep' => '45678-901',
                'rua' => 'Rua das Flores',
                'numero' => '567',
                'complemento' => '',
                'bairro' => 'Savassi',
                'cidade' => 'Belo Horizonte',
                'estado' => 'MG',
                'latitude' => -19.9326,
                'longitude' => -43.9409,
            ],
            [
                'nome' => 'Confeitaria Estrela',
                'telefone' => '11 96666-6666',
                'cep' => '56789-012',
                'rua' => 'Avenida das Estrelas',
                'numero' => '678',
                'complemento' => '',
                'bairro' => 'Vila Mariana',
                'cidade' => 'São Paulo',
                'estado' => 'SP',
                'latitude' => -23.5859,
                'longitude' => -46.6342,    
            ],
            [
                'nome' => 'Bolos e Doces',
                'telefone' => '21 97777-7777',
                'cep' => '67890-123',
                'rua' => 'Rua das Delícias',
                'numero' => '789',
                'complemento' => '',
                'bairro' => 'Copacabana',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'latitude' => -22.9711,
                'longitude' => -43.1822,
            ],
            [
                'nome' => 'Confeitaria Tropical',
                'telefone' => '41 98888-8888',
                'cep' => '78901-234',
                'rua' => 'Rua das Palmeiras',
                'numero' => '890',
                'complemento' => '',
                'bairro' => 'Jardim Botânico',
                'cidade' => 'Curitiba',
                'estado' => 'PR',
                'latitude' => -25.4383,
                'longitude' => -49.2634,
            ],
            [
                'nome' => 'Doce Sabor',
                'telefone' => '61 99999-9999',
                'cep' => '89012-345',
                'rua' => 'Avenida das Flores',
                'numero' => '123',
                'complemento' => '',
                'bairro' => 'Asa Sul',
                'cidade' => 'Brasília',
                'estado' => 'DF',
                'latitude' => -15.7801,
                'longitude' => -47.9292,
            ],          
            [
                'nome' => 'Confeitaria do Pão',
                'telefone' => '51 92222-2222',
                'cep' => '90123-456',
                'rua' => 'Rua do Açúcar',
                'numero' => '234',
                'complemento' => '',
                'bairro' => 'Centro Histórico',
                'cidade' => 'Porto Alegre',
                'estado' => 'RS',
                'latitude' => -30.0346,
                'longitude' => -51.2177,
            ],
            [
                'nome' => 'Doces e Sonhos',
                'telefone' => '71 93333-3333',
                'cep' => '01234-567',
                'rua' => 'Avenida das Sonhos',
                'numero' => '345',
                'complemento' => '',
                'bairro' => 'Barra',
                'cidade' => 'Salvador',
                'estado' => 'BA',
                'latitude' => -12.9711,
                'longitude' => -38.5010,
            ],
            [
                'nome' => 'Confeitaria da Praça',
                'telefone' => '85 94444-4444',
                'cep' => '12345-678',
                'rua' => 'Rua das Praças',
                'numero' => '456',
                'complemento' => '',
                'bairro' => 'Centro',
                'cidade' => 'Fortaleza',
                'estado' => 'CE',
                'latitude' => -3.7172,
                'longitude' => -38.5437,
            ],
            [
                'nome' => 'Confeitaria do Sol',
                'telefone' => '27 95555-5555',
                'cep' => '23456-789',
                'rua' => 'Avenida do Sol',
                'numero' => '567',
                'complemento' => '',
                'bairro' => 'Praia do Canto',
                'cidade' => 'Vitória',
                'estado' => 'ES',
                'latitude' => -20.3155,
                'longitude' => -40.3128,
            ],
        ]);
    }
}
